#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────
# De-insight 一鍵安裝腳本
#
# 用法：
#   curl -fsSL https://raw.githubusercontent.com/KIKIPENG/De-insight/main/install.sh | bash
#
# 安裝位置：
#   ~/.deinsight/app/          原始碼
#   ~/.deinsight/app/.venv/    Python 虛擬環境
#   ~/.local/bin/de-insight    啟動器
# ──────────────────────────────────────────────────────────
set -euo pipefail

# ── 顏色 ────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

info()  { printf "${CYAN}▸${NC} %s\n" "$*"; }
ok()    { printf "${GREEN}✓${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}!${NC} %s\n" "$*"; }
fail()  { printf "${RED}✗${NC} %s\n" "$*" >&2; exit 1; }

# ── 設定 ────────────────────────────────────────────────
REPO_URL="https://github.com/KIKIPENG/De-insight.git"
INSTALL_DIR="${DEINSIGHT_HOME:-$HOME/.deinsight}/app"
BIN_DIR="${HOME}/.local/bin"
LAUNCHER="${BIN_DIR}/de-insight"
MIN_PYTHON_MINOR=11   # Python 3.11+
BRANCH="main"

# ── 檢查 Python ─────────────────────────────────────────
find_python() {
    for cmd in python3.14 python3.13 python3.12 python3.11 python3; do
        if command -v "$cmd" &>/dev/null; then
            local ver
            ver=$("$cmd" -c "import sys; print(f'{sys.version_info.minor}')" 2>/dev/null || echo "0")
            if [ "$ver" -ge "$MIN_PYTHON_MINOR" ]; then
                echo "$cmd"
                return 0
            fi
        fi
    done
    return 1
}

PYTHON=$(find_python) || fail "需要 Python 3.${MIN_PYTHON_MINOR}+，請先安裝。"
PYTHON_VER=$($PYTHON --version)
info "使用 ${PYTHON_VER} ($(command -v $PYTHON))"

# ── 檢查 git ────────────────────────────────────────────
command -v git &>/dev/null || fail "需要 git，請先安裝。"

# ── 下載 / 更新原始碼 ───────────────────────────────────
if [ -d "$INSTALL_DIR/.git" ]; then
    info "更新 De-insight..."
    git -C "$INSTALL_DIR" fetch origin "$BRANCH" --quiet
    git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH" --quiet
    ok "已更新到最新版本"
else
    info "下載 De-insight..."
    mkdir -p "$(dirname "$INSTALL_DIR")"
    git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR" --quiet
    ok "原始碼下載完成"
fi

# ── 建立虛擬環境 ─────────────────────────────────────────
VENV_DIR="$INSTALL_DIR/.venv"
if [ ! -d "$VENV_DIR" ]; then
    info "建立虛擬環境..."
    $PYTHON -m venv "$VENV_DIR"
    ok "虛擬環境建立完成"
fi

# ── 安裝依賴 ─────────────────────────────────────────────
info "安裝依賴（可能需要幾分鐘）..."
"$VENV_DIR/bin/pip" install --quiet --upgrade pip
"$VENV_DIR/bin/pip" install --quiet -r "$INSTALL_DIR/backend/requirements.txt"
ok "依賴安裝完成"

# ── 同步 backend venv（讓 app.py 的 venv 偵測生效）──────
BACKEND_VENV="$INSTALL_DIR/backend/.venv"
if [ ! -d "$BACKEND_VENV" ]; then
    ln -sfn "$VENV_DIR" "$BACKEND_VENV"
    ok "backend venv 已連結"
fi

# ── 建立啟動器 ───────────────────────────────────────────
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" << 'LAUNCHER_EOF'
#!/usr/bin/env bash
# De-insight launcher — generated by install.sh
set -euo pipefail

INSTALL_DIR="${DEINSIGHT_HOME:-$HOME/.deinsight}/app"
VENV_DIR="$INSTALL_DIR/.venv"
REPO_URL="https://raw.githubusercontent.com/KIKIPENG/De-insight/main/install.sh"

case "${1:-}" in
    --update)
        echo "更新 De-insight..."
        curl -fsSL "$REPO_URL" | bash
        exit $?
        ;;
    --uninstall)
        echo "解除安裝 De-insight..."
        rm -rf "$HOME/.deinsight"
        rm -f "$HOME/.local/bin/de-insight"
        echo "已移除。"
        exit 0
        ;;
    --version)
        cd "$INSTALL_DIR" 2>/dev/null && git log --oneline -1 2>/dev/null || echo "unknown"
        exit 0
        ;;
    --help|-h)
        echo "De-insight — AI 思想對話工具"
        echo ""
        echo "用法：de-insight [選項]"
        echo ""
        echo "選項："
        echo "  --update      更新到最新版本"
        echo "  --uninstall   解除安裝"
        echo "  --version     顯示版本"
        echo "  --help        顯示此說明"
        exit 0
        ;;
esac

if [ ! -d "$INSTALL_DIR" ]; then
    echo "De-insight 未安裝。請執行："
    echo "  curl -fsSL $REPO_URL | bash"
    exit 1
fi

# 切到專案目錄（讓相對路徑 import 正常運作）
cd "$INSTALL_DIR"

# 載入 .env（如果存在）
if [ -f .env ]; then
    set -a
    source .env
    set +a
fi

exec "$VENV_DIR/bin/python" tui.py "$@"
LAUNCHER_EOF
chmod +x "$LAUNCHER"
ok "啟動器已安裝到 $LAUNCHER"

# ── 檢查 PATH ───────────────────────────────────────────
NEED_SOURCE=false
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    # 偵測 shell
    SHELL_NAME=$(basename "${SHELL:-/bin/bash}")
    case "$SHELL_NAME" in
        zsh)  RC_FILE="$HOME/.zshrc" ;;
        bash) RC_FILE="$HOME/.bashrc" ;;
        fish) RC_FILE="$HOME/.config/fish/config.fish" ;;
        *)    RC_FILE="$HOME/.profile" ;;
    esac

    PATH_LINE='export PATH="$HOME/.local/bin:$PATH"'
    if [ "$SHELL_NAME" = "fish" ]; then
        PATH_LINE='set -gx PATH $HOME/.local/bin $PATH'
    fi

    # 用更精確的 pattern 檢查，避免被註解或不相關的行誤判
    if [ "$SHELL_NAME" = "fish" ]; then
        GREP_PATTERN='set.*PATH.*\.local/bin'
    else
        GREP_PATTERN='export PATH=.*\.local/bin'
    fi

    if ! grep -qE "$GREP_PATTERN" "$RC_FILE" 2>/dev/null; then
        echo "" >> "$RC_FILE"
        echo "# De-insight" >> "$RC_FILE"
        echo "$PATH_LINE" >> "$RC_FILE"
        ok "已將 ~/.local/bin 加入 $RC_FILE"
    fi

    # 立即在當前 session 生效
    export PATH="$BIN_DIR:$PATH"
    NEED_SOURCE=true
fi

# ── 建立 .env（如果不存在）──────────────────────────────
ENV_FILE="$INSTALL_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << 'ENV_EOF'
# De-insight 設定
# LLM_MODEL=openai/gpt-4o
# OPENAI_API_KEY=sk-...
# OPENAI_API_BASE=https://api.openai.com/v1
ENV_EOF
    warn "已建立 $ENV_FILE，請填入 API key"
fi

# ── 完成 ─────────────────────────────────────────────────
echo ""
printf "${BOLD}${GREEN}De-insight 安裝完成！${NC}\n"
echo ""
if [ "$NEED_SOURCE" = true ]; then
    warn "首次安裝需要重新開啟終端，或執行："
    echo "  source ~/${RC_FILE##*/}"
    echo ""
fi
echo "  啟動：      de-insight"
echo "  設定 API：  \$EDITOR ~/.deinsight/app/.env"
echo "  更新：      de-insight --update"
echo "  解除安裝：  de-insight --uninstall"
echo ""
